### PR TITLE
fixing PSR-4 directory

### PR DESCRIPTION
**Pull request by mikebronner**
This should fix the Laravel 5 issue #10 .

### CODE REVIEW

**Comment by michael-hopkins** [comment]
Darn you PSR! Yeah this looks correct. However, I don't think this would be specific to L5 right? This would just be....across the board the correct way to do ti?

**Comment by mikebronner** [comment]
exactly :)

**Comment by michael-hopkins** [comment]
Thank you very much!

**Comment by mikebronner** [comment]
awesome :) thanks for making this package available, I love it :)

**Pull request merged**
